author: "Katherine Mohr"
title: "katherinemohr.github.io" # TODO: connect to cs.stanford.edu domain
url: "https://katherinemohr.github.io"
repository: "katherinemohr/katherinemohr.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll_sqlite
exclude:
  - _db
  - _plugins
feed:
  collections:
    posts:
      path: "/feed.xml"
collections:
  fragments:
    output: true
    permalink: /:collection/:title
  drafts:
    output: true
  other:
    output: true
    permalink: /:title
  llm_sites:
    output: true
    permalink: /llm_sites/:name:output_ext
sqlite:
  - data: posts
    file: &db "_db/clog.db"
    query: SELECT Link, Title, Notes, AddedAt FROM clog WHERE Type = 'post'
  - data: blogs
    file: *db
    query: SELECT Link, Title, Notes, AddedAt FROM clog WHERE Type = 'blog'
  - data: papers
    file: *db
    query: SELECT Link, Title, Authors, Notes, AddedAt FROM clog WHERE Type = 'paper'
  - data: unread
    file: *db
    query: SELECT Link, Title, AddedAt FROM unread WHERE Active = 1
defaults:
  - scope:
      path: ""
    values:
      default_intro: "In the arena, trying to write some things sometimes."
      include_default_intro: false
