author: 'Katherine Mohr'
title: "katherinemohr.github.io" # TODO: connect to cs.stanford.edu domain
url: "https://katherinemohr.github.io"
repository: "katherinemohr/katherinemohr.github.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - "jekyll-github-metadata"
feed: 
  collections:
    posts: 
      path: "/feed.xml"
collections:
  fragments:
    output: true
    permalink: /:collection/:title
  drafts:
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      default_intro: "In the arena, trying to write some things sometimes."
      include_default_intro: false